<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MegaMan.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>MegaMan.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine.Core\Engine.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MonoGame.Framework">
      <HintPath>..\packages\MonoGame.Framework.WindowsDX.3.6.0.1625\lib\net40\MonoGame.Framework.dll</HintPath>
    </Reference>
    <Reference Include="SharpDX">
      <HintPath>..\packages\MonoGame.Framework.WindowsDX.3.6.0.1625\lib\net40\SharpDX.dll</HintPath>
    </Reference>
    <Reference Include="SharpDX.DXGI">
      <HintPath>..\packages\MonoGame.Framework.WindowsDX.3.6.0.1625\lib\net40\SharpDX.DXGI.dll</HintPath>
    </Reference>
    <Reference Include="SharpDX.XInput">
      <HintPath>..\packages\MonoGame.Framework.WindowsDX.3.6.0.1625\lib\net40\SharpDX.XInput.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Forms\CustomNtscForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\DeleteConfigs.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\EngineGraphicsControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Forms\GraphicsDeviceControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Forms\Keyboard.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\LoadConfig.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\MainForm.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Forms\CustomNtscForm.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Forms\Keyboard.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Forms\MainForm.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="lib\32\ntsc.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="lib\64\ntsc.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>